window.MEETINGMATE_API_BASE = window.MEETINGMATE_API_BASE || "http://localhost:8000";
window.MEETINGMATE_AUTH0_DOMAIN = window.MEETINGMATE_AUTH0_DOMAIN || "";
window.MEETINGMATE_AUTH0_CLIENT_ID = window.MEETINGMATE_AUTH0_CLIENT_ID || "";
window.MEETINGMATE_AUTH0_AUDIENCE = window.MEETINGMATE_AUTH0_AUDIENCE || "";
